# Generated by Django 4.1.3 on 2022-11-10 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], max_length=1, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dias')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(blank=True, error_messages={'unique': 'Este DNI ya está registrado.'}, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, default='1990-10-10', null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número sin 0 ni 15', max_length=10, null=True)),
                ('disponibilidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '08:00'), (2, '09:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00'), (14, '21:00'), (15, '22:00'), (16, '23:00')], max_length=2, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='horas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.horas'),
        ),
    ]
