# Generated by Django 4.1.3 on 2022-11-23 20:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miercoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sabado'), ('Do', 'Domingo')], max_length=8, null=True),
        ),
    ]
