# Generated by Django 4.1.3 on 2022-11-30 23:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='cancha_specs',
            field=main.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('T', 'Techada'), ('AL', 'Aire Libre'), ('SC', 'Superficie Cemento'), ('SS', 'Superficie Sintetico'), ('PC', 'Pared Cemento'), ('PB', 'Pared Blindex')], max_length=30, null=True), default=['T'], size=None),
        ),
    ]
