# Generated by Django 4.1.3 on 2022-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número sin 0 ni 15', max_length=10, null=True),
        ),
    ]
