# Generated by Django 4.1.3 on 2022-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil_completo',
            field=models.BooleanField(default=False),
        ),
    ]
