# Generated by Django 4.1.3 on 2022-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
