# Generated by Django 4.1.3 on 2022-12-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jugador_cancha_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='cancha_specs',
        ),
    ]
