# Generated by Django 4.1.3 on 2022-11-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jugador_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='calle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calle'),
        ),
    ]
