# Generated by Django 4.1.3 on 2022-11-23 21:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jugador_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miercoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sabado'), ('Do', 'Domingo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='turnos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=5, null=True),
        ),
    ]
