# Generated by Django 4.1.3 on 2022-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_perfil_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número sin 0 ni 15', max_length=10, null=True),
        ),
    ]
