# Generated by Django 4.1.3 on 2022-11-10 21:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_dias_horas_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='horas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '08:00'), (2, '09:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00'), (14, '21:00'), (15, '22:00'), (16, '23:00')], max_length=50, null=True),
        ),
    ]
