# Generated by Django 4.1.3 on 2022-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jugador_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nivel',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True),
        ),
    ]
