# Generated by Django 4.1.3 on 2022-11-26 00:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jugador_options_remove_jugador_jugador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='tipo_pared',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='tipo_pared',
        ),
        migrations.AddField(
            model_name='complejo',
            name='cancha_specs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Techada'), ('2', 'Aire Libre'), ('3', 'Superficie Cemento'), ('4', 'Superficie Sintetico'), ('5', 'Pared Cemento'), ('6', 'Pared Blindex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='cancha_specs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Techada'), ('2', 'Aire Libre'), ('3', 'Superficie Cemento'), ('4', 'Superficie Sintetico'), ('5', 'Pared Cemento'), ('6', 'Pared Blindex')], max_length=20, null=True),
        ),
    ]
