# Generated by Django 4.1.3 on 2022-11-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jugador_dias_alter_jugador_turnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='jugador',
        ),
        migrations.AddField(
            model_name='jugador',
            name='jugador',
            field=models.ManyToManyField(to='main.cancha'),
        ),
    ]
