# Generated by Django 4.1.3 on 2022-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cancha_jugador_jugador_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='pared_blindex',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='piso_sint',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='techada',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='año',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='superficie',
        ),
        migrations.RemoveField(
            model_name='complejo',
            name='tipo_pared',
        ),
        migrations.AddField(
            model_name='cancha',
            name='cobertura',
            field=models.IntegerField(choices=[(1, 'Techada'), (2, 'Aire Libre')], default=1),
        ),
        migrations.AddField(
            model_name='cancha',
            name='superficie',
            field=models.IntegerField(choices=[(1, 'Cemento'), (2, 'Sintetico')], default=1),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_pared',
            field=models.IntegerField(choices=[(1, 'Cemento'), (2, 'Blindex')], default=1),
        ),
        migrations.AddField(
            model_name='complejo',
            name='altura',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complejo',
            name='calle',
            field=models.CharField(max_length=155),
        ),
    ]
