# Generated by Django 4.1.3 on 2022-11-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_jugador_domingo_alter_jugador_jueves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='grilla',
            field=models.JSONField(default=list),
        ),
    ]
